name: PixivUserDownload
description: PixivUserDownload

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  dio: ^4.0.1
  json_annotation: ^4.3.0
  # GIF合成 https://pub.dev/documentation/image/latest/image/GifEncoder-class.html
  image: ^3.0.8
  archive: ^3.1.6

dev_dependencies:
  json_serializable: ^6.0.1
  # flutter packages pub run build_runner build
  build_runner: ^2.1.4